### ISSUE TITLE
Could you release an updated version of the gem?

### ISSUE THREAD

**Issue by anthonyalberto** [emerose/pbkdf2-ruby#3]
Hello,

Just went across the problem that was fixed regarding encoding in RUby 1.9. It was fixed, but never released on rubygems.

Plus, when I tried to install it manually from the code of this repo, there's a file "benchmark.rb" that doesn't exists and that is in the gemspec file.

I had to remove it in order to install the gem manually.

Thanks!

**Comment by Asmod4n** [comment]
Yes please :(

**Comment by langalex** [comment]
+1

**Comment by alan** [comment]
+1 for this!! Getting the same encoding issue with Ruby 2.0

**Comment by Asmod4n** [comment]
There is another gem which implements pbkdf2, called "armor" available afaik.
For strong crypto I can recommend cryptosphere/rbnacl

Von meinem iPhone gesendet

Am 04.09.2013 um 16:02 schrieb Alan Kennedy notifications@github.com:

**Comment by emerose** [comment]
I've updated the github source, but don't own the rubygems.org entry, so can't do much there.

-sq

**Comment by cpjolicoeur** [comment]
what about at least adding a gemspec file here at a minimum
